# Generated by Django 4.2.17 on 2024-12-13 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_itemimage_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemimage',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='core.item'),
            preserve_default=False,
        ),
    ]
