# Generated by Django 4.2.17 on 2024-12-13 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_itemimage_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemimage',
            name='features',
        ),
    ]
