# Generated by Django 4.2.17 on 2024-12-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_itemimage_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemimage',
            name='features',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
