# Generated by Django 4.2.17 on 2024-12-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='contact_email',
            field=models.EmailField(default='obansa360@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='contact_phone',
            field=models.CharField(default=123, max_length=15),
            preserve_default=False,
        ),
    ]
