# Generated by Django 4.2.17 on 2025-01-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='features',
            field=models.JSONField(default=list),
        ),
    ]
