# Generated by Django 4.2.17 on 2025-01-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_item_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='relatives',
            field=models.ManyToManyField(blank=True, null=True, to='core.item'),
        ),
    ]
