# Generated by Django 4.2.17 on 2025-01-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_item_relatives'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='matric_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
