# Generated by Django 4.2.17 on 2025-01-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_userprofile_matric_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='features',
            new_name='answers',
        ),
        migrations.AddField(
            model_name='item',
            name='questions',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='item',
            name='relatives',
            field=models.ManyToManyField(to='core.item'),
        ),
    ]
