# Generated by Django 4.2.17 on 2025-01-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_item_relatives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='answers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='item',
            name='questions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
