# Generated by Django 4.2.17 on 2025-01-22 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0017_alter_item_answers_alter_item_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=50)),
                ('answers', models.JSONField(blank=True, default=list)),
                ('claimed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_claimed', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim', to='core.item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='proof_images/')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_proof', to='core.claimitem')),
            ],
        ),
    ]
