# Generated by Django 4.2.17 on 2025-01-23 13:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_claimitem_itemproof'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimitem',
            name='claimed_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
