# Generated by Django 4.2.17 on 2025-02-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_claimitem_claimed_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimitem',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='claimitem',
            name='more_info',
            field=models.BooleanField(default=False),
        ),
    ]
